platform :ios, '7.0'

pod 'RETableViewManager', '~> 1.5.10'
pod 'HMSegmentedControl', '~>1.3.0'
pod 'THSegmentedPager', '~> 0.0.4'
pod 'RMStepsController', '~>1.0.1'
pod 'RegexKitLite', '~> 4.0'
pod 'InAppSettingsKit', '~>2.1'
pod 'UIGlossyButton', '~>0.1.0'
pod 'DZNSegmentedControl', '~>1.1'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'AFNetworking', '~>2.4.1'
pod 'MBProgressHUD', '~>0.9'
pod 'PPSSignatureView', '~>0.1.2'